USE alx_book_store;
SELECT
  COLUMN_NAME AS `Field`,
  COLUMN_TYPE AS `Type`,
  IS_NULLABLE AS `Null`,
  COLUMN_DEFAULT AS `Default`,
  COLUMN_KEY AS `Key`,
  EXTRA AS `Extra`,
  ORDINAL_POSITION AS `Position`
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN ('books','Books')
ORDER BY ORDINAL_POSITION;
